name: mutmut

on: [push]

jobs:
  mutmut:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - run: uv run pytest -q

      - run: uv run mutmut run
