name: mutmut

on: [push]

jobs:
  mutmut:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - run: uv run pytest -q

      - run: uv run mutmut run

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mutants
          path: mutants/
